### ISSUE TITLE
An error

### ISSUE THREAD

**Issue by ghost** [misbah4064/drowsinessDetector#1]
Man I failed running this code:
it gives output:

> RuntimeError                              Traceback (most recent call last)
<ipython-input-17-b321e1290034> in <module>
      1 cap = cv2.VideoCapture(0)
      2 hog_face_detector = dlib.get_frontal_face_detector()
      3 dlib_facelandmark = dlib.shape_predictor("shape_predictor_68_face_landmarks.dat")

RuntimeError: Unable to open shape_predictor_68_face_landmarks.dat

**Comment by Abhishek-Dobliyal** [comment]
https://github.com/AKSHAYUBHAT/TensorFace/blob/master/openface/models/dlib/shape_predictor_68_face_landmarks.dat

Download the Model from above link.

**Comment by ghost** [comment]
thanks bro,it works
